language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
addons:
  chrome: stable
  hostname: localhost
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build
  - yarn test
